# Setup
title: Zhao Mianshuo's Blog
description: This is a blog which was bulit by Zhao Mianshuo.
url: https://zhaomianshuo.pages.dev
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Zhao Mianshuo
  url: https://github.com/
  email: zhao-mianshuo@outlook.com
