# _config.yml
# Main configuration file for the Jekyll site

# Site settings
title: Modern Minimalist Blog
email: your-email@example.com
description: >-
  A clean, responsive Jekyll theme with dark mode support
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: null

plugins:
  - jekyll-feed
  - jekyll-paginate

# Theme customization settings
theme_color: "#3498db"
font_family: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
max_width: "800px"
dark_mode: true
code_highlight_theme: "github"

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - demo_index.html
  - Instruction.html
